export const diccionarioCuentas = [
  // ACTIVOS
  { nombre: "Caja", naturaleza: "Activo", rubro: "Caja y Bancos", saldo: "Deudor", representa: "El dinero en efectivo, billetes y monedas de curso legal bajo custodia del ente.", debita: "Cuando ingresa dinero en efectivo por cobros a clientes, ventas al contado o aportes.", acredita: "Cuando se realiza un pago en efectivo o se deposita el dinero en el banco." },
  { nombre: "Banco Misiones Cta. Cte.", naturaleza: "Activo", rubro: "Caja y Bancos", saldo: "Deudor", representa: "Los fondos disponibles depositados en la cuenta corriente de dicha entidad bancaria.", debita: "Cuando se deposita efectivo, cheques de terceros o se reciben transferencias.", acredita: "Análisis de emisiones de cheques propios o transferencias realizadas a terceros." },
  { nombre: "Mercaderías", naturaleza: "Activo", rubro: "Bienes de Cambio", saldo: "Deudor", representa: "Los bienes destinados a la venta en el curso habitual de la actividad comercial del ente.", debita: "Por el valor de incorporación (compra de contado + gastos necesarios de flete o control).", acredita: "Al registrar el Costo de las Mercaderías Vendidas (CMV) tras concretarse una venta." },
  { nombre: "Deudores por Ventas", naturaleza: "Activo", rubro: "Créditos por Ventas", saldo: "Deudor", representa: "Los derechos de cobro que tiene el ente con clientes que compraron mercaderías en cuenta corriente (a crédito de palabra).", debita: "Al concretarse una venta a crédito sin garantía documental.", acredita: "Cuando el cliente abona su deuda en efectivo, transferencia o nos entrega un cheque." },
  { nombre: "Documentos a Cobrar", naturaleza: "Activo", rubro: "Créditos por Ventas / Otros", saldo: "Deudor", representa: "Los pagarés firmados por clientes o terceros a favor del ente.", debita: "Cuando recibimos un pagaré como garantía de una venta o refinanciación.", acredita: "Al cobrar el documento a su vencimiento." },
  { nombre: "Muebles y Útiles", naturaleza: "Activo", rubro: "Bienes de Uso", saldo: "Deudor", representa: "El mobiliario de la empresa (escritorios, sillas Eames, mostradores, estanterías).", debita: "Por la compra e instalación de los muebles correspondientes.", acredita: "Por su venta, desuso o retiro definitivo del patrimonio." },
  { nombre: "Rodados", naturaleza: "Activo", rubro: "Bienes de Uso", saldo: "Deudor", representa: "Los vehículos automotores de propiedad del ente destinados al uso operativo.", debita: "Por la adquisición del vehículo y gastos de patentamiento inicial.", acredita: "Por venta, siniestro o baja del bien." },
  
  // PASIVOS
  { nombre: "Proveedores", naturaleza: "Pasivo", rubro: "Deudas Comerciales", saldo: "Acreedor", representa: "Las obligaciones a pagar con terceros por compras de mercaderías a crédito de palabra.", debita: "Cuando cancelamos la deuda (pagando con efectivo, banco, etc.).", acredita: "Cuando compramos mercadería a crédito de palabra." },
  { nombre: "Documentos a Pagar", naturaleza: "Pasivo", rubro: "Deudas Comerciales / Otras", saldo: "Acreedor", representa: "Los pagarés de propia firma entregados a terceros que instrumentan una obligación cierta.", debita: "Al cancelar el pagaré a su vencimiento.", acredita: "Al firmar y entregar el documento a un proveedor o acreedor." },
  { nombre: "Acreedores Varios", naturaleza: "Pasivo", rubro: "Deudas Otras", saldo: "Acreedor", representa: "Deudas a crédito de palabra por la compra de bienes que NO son mercaderías (ej: comprar computadoras a crédito).", debita: "Al abonar la deuda contraída.", acredita: "Al asumir la obligación por compras no comerciales." },
  
  // PATRIMONIO NETO
  { nombre: "Capital Social", naturaleza: "Patrimonio Neto", rubro: "Capital", saldo: "Acreedor", representa: "El aporte suscrito y asumido por los propietarios al constituir la sociedad.", debita: "Únicamente en reducciones formales de capital autorizadas por ley.", acredita: "En el momento de la constitución o posteriores aumentos de capital aprobado." },
  { nombre: "Resultados No Asignados", naturaleza: "Patrimonio Neto", rubro: "Resultados Acumulados", saldo: "Acreedor/Deudor", representa: "Las ganancias o pérdidas acumuladas de ejercicios anteriores que no tienen un destino específico.", debita: "Por la distribución de dividendos, absorción de pérdidas o constitución de reservas.", acredita: "Al cierre del ejercicio por la ganancia neta obtenida." },

  // INGRESOS Y EGRESOS
  { nombre: "Ventas", naturaleza: "Resultado Positivo", rubro: "Ingresos Operativos", saldo: "Acreedor", representa: "Los ingresos devengados por la comercialización de bienes o prestación de servicios.", debita: "Al cierre del ejercicio económico para refundir cuentas de resultados.", acredita: "Cada vez que se perfecciona una venta, independientemente de su cobro." },
  { nombre: "Costo de Mercaderías Vendidas (CMV)", naturaleza: "Resultado Negativo", rubro: "Costos Operativos", saldo: "Deudor", representa: "El sacrificio económico sacrificado para adquirir las mercaderías que ya se vendieron.", debita: "Inmediatamente después de registrar la venta, por el valor de costo.", acredita: "Al cierre del ejercicio para la refundición de cuentas." },
  { nombre: "Gastos de Alquileres", naturaleza: "Resultado Negativo", rubro: "Gastos de Administración/Comercialización", saldo: "Deudor", representa: "El costo consumido por el uso de inmuebles ajenos durante el período.", debita: "Mensualmente cuando el alquiler se devenga por el paso del tiempo.", acredita: "Al cierre del ejercicio contable." }
];